idf_component_register(SRCS "main.c" "battery.c" "momo_ble.c" "input_logic.c" "input_sound_logic.c" "input_sound.c" "sound_commands.c" "microphone.c" "microphone_logic.c" "wireless.c" "wireless_logic.c" "wireless_crypto.c" INCLUDE_DIRS "." REQUIRES esp_driver_gpio esp_driver_uart esp_driver_usb_serial_jtag esp_driver_i2s esp_timer nvs_flash json bt esp_adc esp_wifi esp_event esp_netif esp-tls mbedtls)
